# Deployoying to clothing app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: i27-clothing-dev
  labels:
    app: i27-clothing-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: i27-clothing-dev
  template:
    metadata:
      labels:
        app: i27-clothing-dev
    spec:
      containers:
        - name: i27-clothing-dev
          image: DIT 
          ports:
            - containerPort: 3000
          env: 
          - name: ENVIRONMENT
            value: "dev"
---
# Service for clothing app
apiVersion: v1  
kind: Service
metadata:
  name: i27-clothing-dev
  labels:
    app: i27-clothing-dev
spec:
  type: NodePort  # ClusterIP
  ports:
    - port: 80 # service port
      targetPort: 3000 # container port
  selector:
    app: i27-clothing-dev